### ISSUE TITLE
Нету котов на карте

### ISSUE THREAD

**Issue by Shionsan** [G3rste/cats#3]
1.16.1

Ни разу в игре котов не видел. В логах наткнулся на такое:

```
23.1.2022 10:31:01 [Warning] Entity with code cats:cat-female has defined InsideBlockCodes for its spawn conditions, but none of these blocks exists, entity is unlikely to spawn.
23.1.2022 10:31:01 [Warning] Entity with code cats:cat-male has defined InsideBlockCodes for its spawn conditions, but none of these blocks exists, entity is unlikely to spawn.

```

**Comment by G3rste** [comment]
You are completely right. This issue is fixed [here](https://github.com/G3rste/cats/pull/2) and will be no longer present in the next feature update. The next update might still take a couple of days though.

**Comment by Shionsan** [comment]
Thanks. Waiting for the update.
